# -*- coding: utf-8 -*-
"""earrth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hN7hqlmQ_1zYi7eMO5-Ys0COz0EKn-Ks
"""

!apt-get install libgeos-3.5.0
!apt-get install libgeos-dev
!pip install https://github.com/matplotlib/basemap/archive/master.zip

!pip install pyproj==1.9.6

# Commented out IPython magic to ensure Python compatibility.
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
# %matplotlib inline


plt.figure(figsize=(8, 8))
m = Basemap(projection='ortho', resolution=None, lat_0=50, lon_0=-100)
m.bluemarble(scale=0.5);